# CREATE A DATABASE CALLED ZARA_STORE

# WE DROP THE DATABASE IF WE HAVE IT CREATED
DROP DATABASE IF EXISTS zara_store;

# AND CREATE IT IF WE DO NOT
CREATE DATABASE zara_store;

# WE USE THE DATABASE OF INSTEREST
USE zara_store;

# CREATE THE DIFFERENT TABLES:

# PRODUCT TYPE TABLE
CREATE TABLE PRODUCT_TYPE (
Type_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Type_category VARCHAR(50) NOT NULL
);

# PRODUCT TABLE
CREATE TABLE PRODUCT(
Product_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Type_ID INTEGER NOT NULL,
Product_name VARCHAR(50) NOT NULL, 
Product_price FLOAT NOT NULL,
Product_size FLOAT NOT NULL, 
Product_color VARCHAR(50) NOT NULL,
FOREIGN KEY (Type_ID) REFERENCES PRODUCT_TYPE (Type_ID)
);

# ESTABLISHMENT TABLE
CREATE TABLE ESTABLISHMENT(
Establishment_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Estblishment_name VARCHAR(50) NOT NULL,
Establishment_location VARCHAR(50) NOT NULL,
Establishment_phone INTEGER NOT NULL, 
Establishment_email VARCHAR(50) NOT NULL
);


# WORKER TABLE
CREATE TABLE WORKER(
Worker_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Establishment_ID INTEGER NOT NULL,
Worker_name VARCHAR(50) NOT NULL,
Worker_department VARCHAR(50) NOT NULL,
Worker_phone INTEGER NOT NULL, 
Worker_contractDate DATETIME NOT NULL,
FOREIGN KEY(Establishment_ID) REFERENCES ESTABLISHMENT (Establishment_ID)
);

# CUSTOMER TABLE
CREATE TABLE CUSTOMER(
Customer_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Customer_name VARCHAR(50) NOT NULL, 
Customer_phone INTEGER NOT NULL, 
Customer_email VARCHAR(50) NOT NULL,
Customer_zip INTEGER NOT NULL
);

# TRANSACTION TABLE
CREATE TABLE TRANSACTION(
Transaction_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
Product_ID INTEGER NOT NULL,
Worker_ID INTEGER NOT NULL,
Customer_ID INTEGER NOT NULL,
Transaction_quantity INTEGER NOT NULL,
Transaction_price FLOAT NOT NULL,
Transaction_date DATETIME NOT NULL,
FOREIGN KEY (Product_ID) REFERENCES PRODUCT (Product_ID),
FOREIGN KEY (Worker_ID) REFERENCES WORKER (Worker_ID),
FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER (Customer_ID)
);
